language: generic
sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null; #To download google cloud sdk.
  - source $HOME/google-cloud-sdk/path.bash.inc #To set updated configuration of google cloud sdk
  - gcloud components update kubectl #install kubectl
  - gcloud auth activate-service-account --key-file service-account.json #similar to iam system, this activates the service account