apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: k8s-multi-com-tls
spec:
  secretName: zoomtail-online
  issuerRef:
    name: letsencrypt-pod
    kind: ClusterIssuer
  commonName: zoomtail.online
  dnsNames:
    - zoomtail.online
    - www.zoomtail.online
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - zoomtail.online
          - www.zoomtail.online